// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydltgieubhhvfqdwyjep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkbHRnaWV1YmhodmZxZHd5amVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjkzMjksImV4cCI6MjA2OTcwNTMyOX0.SAc-AIzvVmyIA6UsIKDo85gmwuJvFYNNiCvhPHny42I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});